name: "Build Dereferenced IDN specs"

on:
  push:
    branches:
      - main
    paths:
      - idn/sailpoint-api.v3.yaml
      - idn/v3/**
      - idn/sailpoint-api.v2024.yaml
      - idn/v2024/**
      - idn/sailpoint-api.v2025.yaml
      - idn/v2025/**
      - idn/sailpoint-api.beta.yaml
      - idn/beta/**
      - nerm/**
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write
  pull-requests: write

jobs:
  dereference_spec:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::176038645705:role/github-action-role
          role-session-name: deploy-developer-site-infra-to-aws
          aws-region: us-east-1
      - name: Checkout PR branch
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install swagger-cli and postman
        run: |
          npm install -g swagger-cli
          npm install -g openapi-to-postmanv2
      - name: Dereference API Specification and build Postman collection
        run: |
          swagger-cli bundle --dereference idn/sailpoint-api.v3.yaml -t yaml -o dereferenced/deref-sailpoint-api.v3.yaml
          openapi2postmanv2 -s dereferenced/deref-sailpoint-api.v3.yaml -o postman/collections/sailpoint-api-v3.json -p -c postman-script/openapi2postman-config.json
          node postman-script/modify-collection.js postman/collections/sailpoint-api-v3.json
          swagger-cli bundle --dereference idn/sailpoint-api.v3.yaml -t json -o dereferenced/deref-sailpoint-api.v3.json
          
          swagger-cli bundle --dereference idn/sailpoint-api.beta.yaml -t yaml -o dereferenced/deref-sailpoint-api.beta.yaml
          openapi2postmanv2 -s dereferenced/deref-sailpoint-api.beta.yaml -o postman/collections/sailpoint-api-beta.json -p -c postman-script/openapi2postman-config.json
          node postman-script/modify-collection.js postman/collections/sailpoint-api-beta.json
          swagger-cli bundle --dereference idn/sailpoint-api.beta.yaml -t json -o dereferenced/deref-sailpoint-api.beta.json

          swagger-cli bundle --dereference nerm/openapi.yaml -t yaml -o dereferenced/deref-sailpoint-api.nerm.yaml
          openapi2postmanv2 -s dereferenced/deref-sailpoint-api.nerm.yaml -o postman/collections/sailpoint-api-nerm.json -p -c postman-script/openapi2postman-config.json

          swagger-cli bundle --dereference idn/sailpoint-api.v2024.yaml -t yaml -o dereferenced/deref-sailpoint-api.v2024.yaml
          openapi2postmanv2 -s dereferenced/deref-sailpoint-api.v2024.yaml -o postman/collections/sailpoint-api-v2024.json -p -c postman-script/openapi2postman-config.json
          node postman-script/modify-collection.js postman/collections/sailpoint-api-v2024.json
          swagger-cli bundle --dereference idn/sailpoint-api.2024.yaml -t json -o dereferenced/deref-sailpoint-api.v2024.json

          swagger-cli bundle --dereference idn/sailpoint-api.v2025.yaml -t yaml -o dereferenced/deref-sailpoint-api.v2025.yaml
          openapi2postmanv2 -s dereferenced/deref-sailpoint-api.v2025.yaml -o postman/collections/sailpoint-api-v2025.json -p -c postman-script/openapi2postman-config.json
          node postman-script/modify-collection.js postman/collections/sailpoint-api-v2025.json
          swagger-cli bundle --dereference idn/sailpoint-api.v2025.yaml -t json -o dereferenced/deref-sailpoint-api.v2025.json

          cd postman-script/update-by-folder-ts
          echo "POSTMAN_API_KEY=${{ secrets.POSTMAN_API_KEY }}" > .env
          npm ci
          npm run v2025
          npm run v2024
          npm run v3
          npm run beta
          npm run nerm
      - uses: stefanzweifel/git-auto-commit-action@v4
