name: "Build Dereferenced IDN specs"

on:
  push:
    branches:
      - main
    paths:
      - idn/sailpoint-api.v3.yaml
      - idn/v3/**
      - idn/sailpoint-api.beta.yaml
      - idn/beta/**
      - nerm/**
  workflow_dispatch:

jobs:
  dereference_spec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install swagger-cli and postman
        run: |
          npm install -g swagger-cli
          npm install -g openapi-to-postmanv2
      - name: Dereference API Specification and build Postman collection
        run: |
          swagger-cli bundle --dereference idn/sailpoint-api.v3.yaml -t yaml -o dereferenced/deref-sailpoint-api.v3.yaml
          openapi2postmanv2 -s dereferenced/deref-sailpoint-api.v3.yaml -o postman/collections/sailpoint-api-v3.json -p -c postman-script/openapi2postman-config.json
          node postman-script/modify-collection.js postman/collections/sailpoint-api-v3.json
          swagger-cli bundle --dereference idn/sailpoint-api.beta.yaml -t yaml -o dereferenced/deref-sailpoint-api.beta.yaml
          openapi2postmanv2 -s dereferenced/deref-sailpoint-api.beta.yaml -o postman/collections/sailpoint-api-beta.json -p -c postman-script/openapi2postman-config.json
          node postman-script/modify-collection.js postman/collections/sailpoint-api-beta.json
          swagger-cli bundle --dereference nerm/openapi.yaml -t yaml -o dereferenced/deref-sailpoint-api.nerm.yaml
          openapi2postmanv2 -s dereferenced/deref-sailpoint-api.nerm.yaml -o postman/collections/sailpoint-api-nerm.json -p -c postman-script/openapi2postman-config.json
          swagger-cli bundle --dereference idn/sailpoint-api.v3.yaml -t json -o dereferenced/deref-sailpoint-api.v3.json
          swagger-cli bundle --dereference idn/sailpoint-api.beta.yaml -t json -o dereferenced/deref-sailpoint-api.beta.json
      - uses: stefanzweifel/git-auto-commit-action@v4

  push_v3_specs_to_postman:
    runs-on: ubuntu-latest
    needs: [dereference_spec]
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Dereference API Specification and build Postman collection
        run: |
          cd postman-script/update-by-folder-ts
          echo POSTMAN_API_KEY="${{ secrets.POSTMAN_API_KEY }}" > .env
          npm ci
          npm run v3

  push_beta_specs_to_postman:
    runs-on: ubuntu-latest
    needs: [dereference_spec]
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Dereference API Specification and build Postman collection
        run: |
          cd postman-script/update-by-folder-ts
          echo POSTMAN_API_KEY="${{ secrets.POSTMAN_API_KEY }}" > .env
          npm ci
          npm run beta


  push_nerm_specs_to_postman:
    runs-on: ubuntu-latest
    needs: [dereference_spec]
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Dereference API Specification and build Postman collection
        run: |
          cd postman-script/update-by-folder-ts
          echo POSTMAN_API_KEY="${{ secrets.POSTMAN_API_KEY }}" > .env
          npm ci
          npm run nerm