name: "Push NERM API Specs to Developer Portal"

on:
  push:
    branches:
      - main
    paths:
      - nerm/**

jobs:
  push_spec_workflow:
    name: Push API spec changes
    runs-on: ubuntu-latest
    steps:
      # Checkout the master branch request to run rsync
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      # Checkout the main branch of api-specs
      - name: Checkout API Specs Repo
        uses: actions/checkout@v2
        with:
          repository: sailpoint-oss/developer.sailpoint.com
          path: developer-community
          ref: main

      - name: Install rsync
        run: |
          sudo apt install rsync grsync

      - name: Sync files between folders
        run: |
          CURRENT_SPEC_PATH="nerm/"
          NEW_API_SPEC_PATH="developer-community/static/api-specs/nerm/"

          rsync -cav --delete $CURRENT_SPEC_PATH $NEW_API_SPEC_PATH 

          cd developer-community
          git status

          git config --unset-all http.https://github.com/.extraheader
          git config --local user.email "tyler.mairose@sailpoint.com"
          git config --local user.name "GitHub Action Bot"

          git add .
          git commit -m "Automated commit by github action: ${{ github.run_id }}"

          git status

          git remote set-url origin https://${{secrets.API_SPEC_PAT}}@github.com/sailpoint-oss/developer.sailpoint.com.git

          git remote -v

          git push
