name: Generate Vacuum Reports

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - dereferenced/deref-sailpoint-api.v2024.yaml
      - dereferenced/deref-sailpoint-api.beta.yaml
      - dereferenced/deref-sailpoint-api.nerm.yaml
      - dereferenced/deref-sailpoint-api.v3.yaml

jobs:
  generate-reports:
    name: Generate Vacuum Reports
    runs-on: macos-latest
    strategy:
      matrix:
        spec-name: [v2024, beta, nerm, v3]
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Install Vacuum
        run: |
          brew install daveshanley/vacuum/vacuum

      - name: Generate Vacuum Reports
        run: |
          mkdir -p reports
          vacuum html-report ./dereferenced/deref-sailpoint-api.${{ matrix.spec-name }}.yaml ./reports/${{ matrix.spec-name }}.html

      - name: Commit Reports
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update ${matrix.spec-name} report"
          file_pattern: |
            reports/${{ matrix.spec-name }}.html
