name: "Auto Release on Dereferenced Spec Changes"

on:
  push:
    branches:
      - main
    paths:
      - dereferenced/**
  workflow_dispatch:
  schedule:
    # Run daily at 2 AM UTC to check for any missed changes
    - cron: '0 2 * * *'

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name 'developer-relations-sp'
          git config --global user.email 'devrel-service@sailpoint.com'
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Run simple release automation
        run: |
          node scripts/simple-release-automation.js

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          github_token: ${{ env.GH_TOKEN }}
          commit_message: "Update dereferenced specifications"
          commit_author: developer-relations-sp <devrel-service@sailpoint.com>